version: '3.7'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
     #volumes:
     # - './services/users:/usr/src/app'
    #ports:
     # - 5001:5000
    expose:
      - 5000 
    environment:
       #- FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test

    depends_on:  # nuevo
      - users-db

  users-db:  # nuevo
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
#ports:
    #  - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  nginx:
    container_name: nginx
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    ports:
      - 3007:80
    depends_on:
      - users

