# base image
FROM python:3.8.5-alpine
# instalando dependencias
RUN apk update && \
    apk add --virtual build-deps gcc python3-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd
# estableciendo directorio de trabajo
WORKDIR /usr/src/app
# agregando e instalando requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt
# agregando entrypoint.sh
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh
RUN chmod +x /usr/src/app/entrypoint-prod.sh
# agregando app
COPY . /usr/src/app
# ejecutar server
CMD ["/usr/src/app/entrypoint-prod.sh"]
